require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

permissions_path = '../node_modules/react-native-permissions/ios'

pod 'Base64'
pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary/Permission-PhotoLibrary.podspec"
pod 'SexyTooltip',:git => 'https://github.com/prscX/SexyTooltip.git'
pod 'RNTooltips', :path => '../node_modules/react-native-tooltips/ios'



target 'Notesnook' do
  config = use_native_modules!
  pod 'MMKV'
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )
  pod 'react-native-mmkv-storage', :path => '../node_modules/react-native-mmkv-storage/react-native-mmkv-storage.podspec'
 
  # for share extension
  target 'Make Note' do
    use_native_modules!
    inherit! :complete
    
  end
  
  target 'NotesnookTests' do
   
    # Pods for testing
  end

  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
 # use_flipper!
 # post_install do |installer|
 #   flipper_post_install(installer)
 # end
end



target 'Notesnook-tvOS' do
  # Pods for Notesnook-tvOS

  target 'Notesnook-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end
