/*
This file is part of the Notesnook project (https://notesnook.com/)

Copyright (C) 2023 Streetwriters (Private) Limited

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// THIS FILE IS AUTO-GENERATED BY scripts/generate-locale-loaders.mjs. DO NOT EDIT.

export const LOCALE_LOADERS = {
  en: () => require("@notesnook/intl/dist/locales/$en.json").messages,
  de: () => require("@notesnook/intl/dist/locales/$de.json").messages,
  es: () => require("@notesnook/intl/dist/locales/$es.json").messages,
  fr: () => require("@notesnook/intl/dist/locales/$fr.json").messages,
  it: () => require("@notesnook/intl/dist/locales/$it.json").messages,
  nl: () => require("@notesnook/intl/dist/locales/$nl.json").messages,
  pl: () => require("@notesnook/intl/dist/locales/$pl.json").messages,
  "pt-BR": () => require("@notesnook/intl/dist/locales/$pt-BR.json").messages,
  ru: () => require("@notesnook/intl/dist/locales/$ru.json").messages,
  tr: () => require("@notesnook/intl/dist/locales/$tr.json").messages,
  uk: () => require("@notesnook/intl/dist/locales/$uk.json").messages
};
