blank_issues_enabled: true
contact_links:
  - name: Notesnook Discord Community
    url: https://go.notesnook.com/discord
    about: Reach out to us directly & discuss your issues, suggestions & other feedback!
