import {
  mdiAttachment,
  mdiBorderHorizontal,
  mdiCheck,
  mdiChevronDown,
  mdiCodeBraces,
  mdiCodeTags,
  mdiDotsVertical,
  mdiFormatAlignCenter,
  mdiFormatAlignJustify,
  mdiFormatAlignLeft,
  mdiFormatAlignRight,
  mdiFormatBold,
  mdiFormatClear,
  mdiFormatColorHighlight,
  mdiFormatColorText,
  mdiFormatItalic,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiFormatQuoteClose,
  mdiFormatStrikethrough,
  mdiFormatSubscript,
  mdiFormatSuperscript,
  mdiFormatTextdirectionLToR,
  mdiFormatTextdirectionRToL,
  mdiFormatUnderline,
  mdiImage,
  mdiInvertColorsOff,
  mdiLinkPlus,
  mdiLoading,
  mdiTable,
  mdiTableBorder,
  mdiTableRowPlusAfter,
  mdiTableRowPlusBefore,
  mdiTableRowRemove,
  mdiTableColumnPlusAfter,
  mdiTableColumnPlusBefore,
  mdiTableColumnRemove,
  mdiUploadOutline,
  mdiPlus,
  mdiSquareRoundedBadgeOutline,
  mdiFormatColorFill,
  mdiBorderAllVariant,
  mdiClose,
  mdiSortDescending,
  mdiArrowExpandRight,
  mdiArrowExpandLeft,
  mdiArrowExpandDown,
  mdiArrowExpandUp,
  mdiTrashCanOutline,
  mdiTableMergeCells,
  mdiTableSplitCell,
  mdiDeleteOutline,
  mdiDownloadOutline,
  mdiFormatListCheckbox,
  mdiDrag,
  mdiCheckboxMarkedOutline,
  mdiChevronUp,
} from "@mdi/js";

export const Icons = {
  bold: mdiFormatBold,
  italic: mdiFormatItalic,
  underline: mdiFormatUnderline,
  strikethrough: mdiFormatStrikethrough,
  code: mdiCodeTags,
  alignCenter: mdiFormatAlignCenter,
  alignLeft: mdiFormatAlignLeft,
  alignRight: mdiFormatAlignRight,
  alignJustify: mdiFormatAlignJustify,
  subscript: mdiFormatSubscript,
  superscript: mdiFormatSuperscript,
  horizontalRule: mdiBorderHorizontal,
  codeblock: mdiCodeBraces,
  blockquote: mdiFormatQuoteClose,
  formatClear: mdiFormatClear,
  ltr: mdiFormatTextdirectionLToR,
  rtl: mdiFormatTextdirectionRToL,
  numberedList: mdiFormatListNumbered,
  bulletList: mdiFormatListBulleted,
  highlight: mdiFormatColorHighlight,
  textColor: mdiFormatColorText,
  link: mdiLinkPlus,
  image: mdiImage,
  colorClear: mdiInvertColorsOff,
  check: mdiCheck,
  checkbox: mdiCheckboxMarkedOutline,
  loading: mdiLoading,
  more: mdiDotsVertical,
  upload: mdiUploadOutline,
  attachment: mdiAttachment,
  table: mdiTable,
  insertRowBelow: mdiPlus,
  insertRowAbove: mdiTableRowPlusBefore,
  moveRowDown: mdiArrowExpandDown,
  moveRowUp: mdiArrowExpandUp,
  deleteRow: mdiTableRowRemove,
  toggleHeaderRow: mdiTableBorder,
  insertColumnRight: mdiTableColumnPlusAfter,
  insertColumnLeft: mdiTableColumnPlusBefore,
  moveColumnRight: mdiArrowExpandRight,
  moveColumnLeft: mdiArrowExpandLeft,
  deleteColumn: mdiTableColumnRemove,
  cellProperties: mdiSquareRoundedBadgeOutline,
  backgroundColor: mdiFormatColorFill,
  borderColor: mdiBorderAllVariant,
  sortDesc: mdiSortDescending,
  deleteTable: mdiTrashCanOutline,
  mergeCells: mdiTableMergeCells,
  splitCells: mdiTableSplitCell,
  checklist: mdiFormatListCheckbox,
  dragHandle: mdiDrag,

  plus: mdiPlus,
  close: mdiClose,
  delete: mdiDeleteOutline,
  download: mdiDownloadOutline,
  chevronDown: mdiChevronDown,
  chevronUp: mdiChevronUp,
};

export type IconNames = keyof typeof Icons;
