module.exports = [
  { name: "Plain text", shortname: "plaintext" },
  { name: "HTML, XML", shortname: "xml" },
  { name: "Bash", shortname: "bash" },
  { name: "C", shortname: "c" },
  { name: "C++", shortname: "cpp" },
  { name: "C#", shortname: "csharp" },
  { name: "CSS", shortname: "css" },
  { name: "Markdown", shortname: "markdown" },
  { name: "Diff", shortname: "diff" },
  { name: "Ruby", shortname: "ruby" },
  { name: "Go", shortname: "go" },
  { name: "TOML, also INI", shortname: "ini" },
  { name: "Java", shortname: "java" },
  { name: "Javascript", shortname: "javascript" },
  { name: "JSON", shortname: "json" },
  { name: "Kotlin", shortname: "kotlin" },
  { name: "Less", shortname: "less" },
  { name: "Lua", shortname: "lua" },
  { name: "Makefile", shortname: "makefile" },
  { name: "Perl", shortname: "perl" },
  { name: "Objective-C", shortname: "objectivec" },
  { name: "php", shortname: "php" },
  { name: "PHP template", shortname: "php-template" },
  { name: "Python", shortname: "python" },
  { name: "python-repl", shortname: "python-repl" },
  { name: "R", shortname: "r" },
  { name: "Rust", shortname: "rust" },
  { name: "SCSS", shortname: "scss" },
  { name: "Shell Session", shortname: "shell" },
  { name: "SQL", shortname: "sql" },
  { name: "Swift", shortname: "swift" },
  { name: "YAML", shortname: "yaml" },
  { name: "TypeScript", shortname: "typescript" },
  { name: "Visual Basic .NET", shortname: "vbnet" },
  { name: "1C:Enterprise", shortname: "1c" },
  { name: "Augmented Backus-Naur Form", shortname: "abnf" },
  { name: "Apache Access Log", shortname: "accesslog" },
  { name: "ActionScript", shortname: "actionscript" },
  { name: "Ada", shortname: "ada" },
  { name: "AngelScript", shortname: "angelscript" },
  { name: "Apache config", shortname: "apache" },
  { name: "AppleScript", shortname: "applescript" },
  { name: "ArcGIS Arcade", shortname: "arcade" },
  { name: "Arduino", shortname: "arduino" },
  { name: "ARM Assembly", shortname: "armasm" },
  { name: "AsciiDoc", shortname: "asciidoc" },
  { name: "AspectJ", shortname: "aspectj" },
  { name: "AutoHotkey", shortname: "autohotkey" },
  { name: "AutoIt", shortname: "autoit" },
  { name: "AVR Assembly", shortname: "avrasm" },
  { name: "Awk", shortname: "awk" },
  { name: "X++", shortname: "axapta" },
  { name: "BASIC", shortname: "basic" },
  { name: "Backus–Naur Form", shortname: "bnf" },
  { name: "Brainfuck", shortname: "brainfuck" },
  { name: "C/AL", shortname: "cal" },
  { name: "Cap’n Proto", shortname: "capnproto" },
  { name: "Ceylon", shortname: "ceylon" },
  { name: "Clean", shortname: "clean" },
  { name: "Clojure", shortname: "clojure" },
  { name: "Clojure REPL", shortname: "clojure-repl" },
  { name: "CMake", shortname: "cmake" },
  { name: "CoffeeScript", shortname: "coffeescript" },
  { name: "Coq", shortname: "coq" },
  { name: "Caché Object Script", shortname: "cos" },
  { name: "crmsh", shortname: "crmsh" },
  { name: "Crystal", shortname: "crystal" },
  { name: "CSP", shortname: "csp" },
  { name: "D", shortname: "d" },
  { name: "Dart", shortname: "dart" },
  { name: "Delphi", shortname: "delphi" },
  { name: "Django", shortname: "django" },
  { name: "DNS Zone", shortname: "dns" },
  { name: "Dockerfile", shortname: "dockerfile" },
  { name: "Batch file (DOS)", shortname: "dos" },
  { name: "dsconfig", shortname: "dsconfig" },
  { name: "Device Tree", shortname: "dts" },
  { name: "Dust", shortname: "dust" },
  { name: "Extended Backus-Naur Form", shortname: "ebnf" },
  { name: "Elixir", shortname: "elixir" },
  { name: "Elm", shortname: "elm" },
  { name: "ERB", shortname: "erb" },
  { name: "Erlang REPL", shortname: "erlang-repl" },
  { name: "Erlang", shortname: "erlang" },
  { name: "Excel formulae", shortname: "excel" },
  { name: "FIX", shortname: "fix" },
  { name: "Flix", shortname: "flix" },
  { name: "Fortran", shortname: "fortran" },
  { name: "F#", shortname: "fsharp" },
  { name: "GAMS", shortname: "gams" },
  { name: "GAUSS", shortname: "gauss" },
  { name: "G-code (ISO 6983)", shortname: "gcode" },
  { name: "Gherkin", shortname: "gherkin" },
  { name: "GLSL", shortname: "glsl" },
  { name: "GML", shortname: "gml" },
  { name: "Golo", shortname: "golo" },
  { name: "Gradle", shortname: "gradle" },
  { name: "Groovy", shortname: "groovy" },
  { name: "HAML", shortname: "haml" },
  { name: "Handlebars", shortname: "handlebars" },
  { name: "Haskell", shortname: "haskell" },
  { name: "Haxe", shortname: "haxe" },
  { name: "HSP", shortname: "hsp" },
  { name: "HTTP", shortname: "http" },
  { name: "Hy", shortname: "hy" },
  { name: "Inform 7", shortname: "inform7" },
  { name: "IRPF90", shortname: "irpf90" },
  { name: "ISBL", shortname: "isbl" },
  { name: "JBoss CLI", shortname: "jboss-cli" },
  { name: "Julia", shortname: "julia" },
  { name: "Julia REPL", shortname: "julia-repl" },
  { name: "Lasso", shortname: "lasso" },
  { name: "LaTeX", shortname: "latex" },
  { name: "LDIF", shortname: "ldif" },
  { name: "Leaf", shortname: "leaf" },
  { name: "Lisp", shortname: "lisp" },
  { name: "LiveCode", shortname: "livecodeserver" },
  { name: "LiveScript", shortname: "livescript" },
  { name: "LLVM IR", shortname: "llvm" },
  { name: "LSL (Linden Scripting Language)", shortname: "lsl" },
  { name: "Mathematica", shortname: "mathematica" },
  { name: "Matlab", shortname: "matlab" },
  { name: "Maxima", shortname: "maxima" },
  { name: "MEL", shortname: "mel" },
  { name: "Mercury", shortname: "mercury" },
  { name: "MIPS Assembly", shortname: "mipsasm" },
  { name: "Mizar", shortname: "mizar" },
  { name: "Mojolicious", shortname: "mojolicious" },
  { name: "Monkey", shortname: "monkey" },
  { name: "MoonScript", shortname: "moonscript" },
  { name: "N1QL", shortname: "n1ql" },
  { name: "Nested Text", shortname: "nestedtext" },
  { name: "Nginx config", shortname: "nginx" },
  { name: "Nim", shortname: "nim" },
  { name: "Nix", shortname: "nix" },
  { name: "Node REPL", shortname: "node-repl" },
  { name: "NSIS", shortname: "nsis" },
  { name: "OCaml", shortname: "ocaml" },
  { name: "OpenSCAD", shortname: "openscad" },
  { name: "Oxygene", shortname: "oxygene" },
  { name: "Parser3", shortname: "parser3" },
  { name: "Packet Filter config", shortname: "pf" },
  { name: "PostgreSQL", shortname: "pgsql" },
  { name: "Pony", shortname: "pony" },
  { name: "PowerShell", shortname: "powershell" },
  { name: "Processing", shortname: "processing" },
  { name: "Python profiler", shortname: "profile" },
  { name: "Prolog", shortname: "prolog" },
  { name: ".properties", shortname: "properties" },
  { name: "Protocol Buffers", shortname: "protobuf" },
  { name: "Puppet", shortname: "puppet" },
  { name: "PureBASIC", shortname: "purebasic" },
  { name: "Q", shortname: "q" },
  { name: "QML", shortname: "qml" },
  { name: "ReasonML", shortname: "reasonml" },
  { name: "RenderMan RIB", shortname: "rib" },
  { name: "Roboconf", shortname: "roboconf" },
  { name: "Microtik RouterOS script", shortname: "routeros" },
  { name: "RenderMan RSL", shortname: "rsl" },
  { name: "Oracle Rules Language", shortname: "ruleslanguage" },
  { name: "SAS", shortname: "sas" },
  { name: "Scala", shortname: "scala" },
  { name: "Scheme", shortname: "scheme" },
  { name: "Scilab", shortname: "scilab" },
  { name: "Smali", shortname: "smali" },
  { name: "Smalltalk", shortname: "smalltalk" },
  { name: "SML (Standard ML)", shortname: "sml" },
  { name: "SQF", shortname: "sqf" },
  { name: "Stan", shortname: "stan" },
  { name: "Stata", shortname: "stata" },
  { name: "STEP Part 21", shortname: "step21" },
  { name: "Stylus", shortname: "stylus" },
  { name: "SubUnit", shortname: "subunit" },
  { name: "Tagger Script", shortname: "taggerscript" },
  { name: "Test Anything Protocol", shortname: "tap" },
  { name: "Tcl", shortname: "tcl" },
  { name: "Thrift", shortname: "thrift" },
  { name: "TP", shortname: "tp" },
  { name: "Twig", shortname: "twig" },
  { name: "Vala", shortname: "vala" },
  { name: "Visual Basic .NET", shortname: "vbnet" },
  { name: "VBScript", shortname: "vbscript" },
  { name: "VBScript in HTML", shortname: "vbscript-html" },
  { name: "Verilog", shortname: "verilog" },
  { name: "VHDL", shortname: "vhdl" },
  { name: "Vim Script", shortname: "vim" },
  { name: "WebAssembly", shortname: "wasm" },
  { name: "Wren", shortname: "wren" },
  { name: "Intel x86 Assembly", shortname: "x86asm" },
  { name: "XL", shortname: "xl" },
  { name: "XQuery", shortname: "xquery" },
  { name: "Zephir", shortname: "zephir" },
];
