export const ACTIONS = {
  NOTES: 'note',
  NOTEBOOKS: 'notebook',
  TRASH: 'trash',
  TAGS: 'tags',
  PINNED: 'pinned',
  FAVORITES: 'favorites',
  SELECTION_MODE: 'selectionMode',
  SELECTED_ITEMS: 'selectedItemsList',
  THEME: 'theme',
  MODAL_NAVIGATOR: 'modalNavigator',
  CLEAR_SELECTION: 'clearSelection',
  LOGIN_NAVIGATOR: 'loginNavigator',
  CURRENT_EDITING_NOTE: 'currentEditingNote',
  COLORS: 'colorNotes',
  SEARCH_RESULTS: 'searchResults',
  USER: 'getUser',
  CURRENT_SCREEN: 'currentScreen',
  SETTINGS: 'getSettings',
};
