name: Test @notesnook/editor

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "packages/editor/**"
      # re-run workflow if workflow file changes
      - ".github/workflows/editor.tests.yml"
  pull_request:
    branches:
      - "master"
    paths:
      - "packages/editor/**"
      # re-run workflow if workflow file changes
      - ".github/workflows/editor.tests.yml"
    types:
      - "ready_for_review"
      - "opened"
      - "synchronize"
      - "reopened"

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup-node-with-cache

      - name: Install packages
        run: |
          bun ci
          bun run bootstrap -- --scope=editor

      - name: Build editor
        run: bun tx @notesnook/editor:build

      - name: Run all @notesnook/editor tests
        run: bun tx @notesnook/editor:test
