name: Publish @notesnook/theme-builder

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup-node-with-cache

      - name: Install packages
        run: |
          bun ci
          bun run bootstrap -- --scope=themebuilder

      - name: Setup environment
        run: |
          echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV

      - name: Generate build
        run: bun run build:theme-builder

      - name: Publish to Cloudflare Pages
        run: bunx --silent wrangler pages deploy --project-name=notesnook-theme-builder ./apps/theme-builder/build/
